[package]
name = "contains_duplicate"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sol1"
path = "src/sol1.rs"

[[bin]]
name = "sol2"
path = "src/sol2.rs"

[[bin]]
name = "sol3"
path = "src/sol3.rs"

[dependencies]
rand = "0.10.0"
sorting_rs = "1.2.10"
